-- init file for H2 database

-- AUTHOR table
INSERT INTO AUTHOR (FIRSTNAME, LASTNAME) VALUES ('Carl Jonas Love', 'Almqvist');
INSERT INTO AUTHOR (FIRSTNAME, LASTNAME) VALUES ('Lena', 'Andersson');
INSERT INTO AUTHOR (FIRSTNAME, LASTNAME) VALUES ('Per Anders', 'Fogelstrom');
INSERT INTO AUTHOR (FIRSTNAME, LASTNAME) VALUES ('Jonas', 'Gardell');
INSERT INTO AUTHOR (FIRSTNAME, LASTNAME) VALUES ('Graham', 'Greene');
INSERT INTO AUTHOR (FIRSTNAME, LASTNAME) VALUES ('Jan', 'Guillou');
INSERT INTO AUTHOR (FIRSTNAME, LASTNAME) VALUES ('Eyvind', 'Johnson');
INSERT INTO AUTHOR (FIRSTNAME, LASTNAME) VALUES ('Jonas Hassen', 'Khemiri');
INSERT INTO AUTHOR (FIRSTNAME, LASTNAME) VALUES ('Selma', 'Lagerlof');
INSERT INTO AUTHOR (FIRSTNAME, LASTNAME) VALUES ('Jens', 'Lapidus');
INSERT INTO AUTHOR (FIRSTNAME, LASTNAME) VALUES ('Stieg', 'Larsson');
INSERT INTO AUTHOR (FIRSTNAME, LASTNAME) VALUES ('Ivar', 'Lo-Johansson');
INSERT INTO AUTHOR (FIRSTNAME, LASTNAME) VALUES ('Ulf', 'Lundell');
INSERT INTO AUTHOR (FIRSTNAME, LASTNAME) VALUES ('Vilhelm', 'Moberg');
INSERT INTO AUTHOR (FIRSTNAME, LASTNAME) VALUES ('Bengt', 'Ohlsson');
INSERT INTO AUTHOR (FIRSTNAME, LASTNAME) VALUES ('Klas', 'Ostergren');
INSERT INTO AUTHOR (FIRSTNAME, LASTNAME) VALUES ('Hjalmar', 'Soderberg');
INSERT INTO AUTHOR (FIRSTNAME, LASTNAME) VALUES ('August', 'Strindberg');
INSERT INTO AUTHOR (FIRSTNAME, LASTNAME) VALUES ('Elin', 'Wagner');
INSERT INTO AUTHOR (FIRSTNAME, LASTNAME) VALUES ('Maj', 'Wahloo');
INSERT INTO AUTHOR (FIRSTNAME, LASTNAME) VALUES ('Irving', 'Wallace');
INSERT INTO AUTHOR (FIRSTNAME, LASTNAME) VALUES ('Peter', 'Weiss');

-- BOOK TABLE
INSERT INTO BOOK (AUTHOR_ID, TITLE, RELEASE_YEAR, DESCRIPTION) VALUES(1, 'Det gar an', 1839, 'Det gar an-Carl Jonas Love Almqvist-1839');
INSERT INTO BOOK (AUTHOR_ID, TITLE, RELEASE_YEAR, DESCRIPTION) VALUES(18, 'The Red Room', 1879, 'The Red Room-August Strindberg-1879');
INSERT INTO BOOK (AUTHOR_ID, TITLE, RELEASE_YEAR, DESCRIPTION) VALUES(18, 'The Son of a Servant', 1886, 'The Son of a Servant-August Strindberg-1886');
INSERT INTO BOOK (AUTHOR_ID, TITLE, RELEASE_YEAR, DESCRIPTION) VALUES(17, 'Farvillelser', 1895, 'Farvillelser-Hjalmar Soderberg-1895');
INSERT INTO BOOK (AUTHOR_ID, TITLE, RELEASE_YEAR, DESCRIPTION) VALUES(17, 'Martin Bircks Youth', 1901, 'Martin Bircks Youth-Hjalmar Soderberg-1901');
INSERT INTO BOOK (AUTHOR_ID, TITLE, RELEASE_YEAR, DESCRIPTION) VALUES(18, 'Alone', 1903, 'Alone-August Strindberg-1903');
INSERT INTO BOOK (AUTHOR_ID, TITLE, RELEASE_YEAR, DESCRIPTION) VALUES(17, 'Doctor Glas', 1905, 'Doctor Glas-Hjalmar Soderberg-1905');
INSERT INTO BOOK (AUTHOR_ID, TITLE, RELEASE_YEAR, DESCRIPTION) VALUES(19, 'Norrtullsligan', 1908, 'Norrtullsligan-Elin Wagner-1908');
INSERT INTO BOOK (AUTHOR_ID, TITLE, RELEASE_YEAR, DESCRIPTION) VALUES(17, 'The Serious Game', 1912, 'The Serious Game-Hjalmar Soderberg-1912');
INSERT INTO BOOK (AUTHOR_ID, TITLE, RELEASE_YEAR, DESCRIPTION) VALUES(9, 'The Emperor of Portugallia', 1914, 'The Emperor of Portugallia-Selma Lagerlof-1914');
INSERT INTO BOOK (AUTHOR_ID, TITLE, RELEASE_YEAR, DESCRIPTION) VALUES(5, 'England Made Me', 1935, 'England Made Me-Graham Greene-1935');
INSERT INTO BOOK (AUTHOR_ID, TITLE, RELEASE_YEAR, DESCRIPTION) VALUES(12, 'Kungsgatan', 1935, 'Kungsgatan-Ivar Lo-Johansson-1935');
INSERT INTO BOOK (AUTHOR_ID, TITLE, RELEASE_YEAR, DESCRIPTION) VALUES(14, 'Somnlos', 1937, 'Somnlos-Vilhelm Moberg-1937');
INSERT INTO BOOK (AUTHOR_ID, TITLE, RELEASE_YEAR, DESCRIPTION) VALUES(7, 'Grupp Krilon', 1941, 'Grupp Krilon-Eyvind Johnson-1941');
INSERT INTO BOOK (AUTHOR_ID, TITLE, RELEASE_YEAR, DESCRIPTION) VALUES(7, 'Krilons resa', 1942, 'Krilons resa-Eyvind Johnson-1942');
INSERT INTO BOOK (AUTHOR_ID, TITLE, RELEASE_YEAR, DESCRIPTION) VALUES(7, 'Krilon sjalv', 1943, 'Krilon sjalv-Eyvind Johnson-1943');
INSERT INTO BOOK (AUTHOR_ID, TITLE, RELEASE_YEAR, DESCRIPTION) VALUES(3, 'City of My Dreams', 1960, 'City of My Dreams-Per Anders Fogelstrom-1960');
INSERT INTO BOOK (AUTHOR_ID, TITLE, RELEASE_YEAR, DESCRIPTION) VALUES(3, 'Children of Their City', 1962, 'Children of Their City-Per Anders Fogelstrom-1962');
INSERT INTO BOOK (AUTHOR_ID, TITLE, RELEASE_YEAR, DESCRIPTION) VALUES(21, 'The Prize', 1962, 'The Prize-Irving Wallace-1962');
INSERT INTO BOOK (AUTHOR_ID, TITLE, RELEASE_YEAR, DESCRIPTION) VALUES(3, 'Remember the City', 1964, 'Remember the City-Per Anders Fogelstrom-1964');
INSERT INTO BOOK (AUTHOR_ID, TITLE, RELEASE_YEAR, DESCRIPTION) VALUES(20, 'The Story of a Crime', 1965, 'The Story of a Crime-Maj Wahloo-1965');
INSERT INTO BOOK (AUTHOR_ID, TITLE, RELEASE_YEAR, DESCRIPTION) VALUES(3, 'In a City Transformed', 1966, 'In a City Transformed-Per Anders Fogelstrom-1966');
INSERT INTO BOOK (AUTHOR_ID, TITLE, RELEASE_YEAR, DESCRIPTION) VALUES(3, 'Stad i varlden', 1968, 'Stad i varlden-Per Anders Fogelstrom-1968');
INSERT INTO BOOK (AUTHOR_ID, TITLE, RELEASE_YEAR, DESCRIPTION) VALUES(16, 'Attila', 1975, 'Attila-Klas Ostergren-1975');
INSERT INTO BOOK (AUTHOR_ID, TITLE, RELEASE_YEAR, DESCRIPTION) VALUES(22, 'The Aesthetics of Resistance', 1975, 'The Aesthetics of Resistance-Peter Weiss-1975');
INSERT INTO BOOK (AUTHOR_ID, TITLE, RELEASE_YEAR, DESCRIPTION) VALUES(13, 'Jack', 1976, 'Jack-Ulf Lundell-1976');
INSERT INTO BOOK (AUTHOR_ID, TITLE, RELEASE_YEAR, DESCRIPTION) VALUES(16, 'Fantomerna', 1978, 'Fantomerna-Klas Ostergren-1978');
INSERT INTO BOOK (AUTHOR_ID, TITLE, RELEASE_YEAR, DESCRIPTION) VALUES(16, 'Gentlemen', 1980, 'Gentlemen-Klas Ostergren-1980');
INSERT INTO BOOK (AUTHOR_ID, TITLE, RELEASE_YEAR, DESCRIPTION) VALUES(6, 'Evil', 1981, 'Evil-Jan Guillou-1981');
INSERT INTO BOOK (AUTHOR_ID, TITLE, RELEASE_YEAR, DESCRIPTION) VALUES(16, 'Fattiga riddare och stora svenskar', 1983, 'Fattiga riddare och stora svenskar-Klas Ostergren-1983');
INSERT INTO BOOK (AUTHOR_ID, TITLE, RELEASE_YEAR, DESCRIPTION) VALUES(8, 'Ett oga rott', 2003, 'Ett oga rott-Jonas Hassen Khemiri-2003');
INSERT INTO BOOK (AUTHOR_ID, TITLE, RELEASE_YEAR, DESCRIPTION) VALUES(15, 'Gregorius', 2004, 'Gregorius-Bengt Ohlsson-2004');
INSERT INTO BOOK (AUTHOR_ID, TITLE, RELEASE_YEAR, DESCRIPTION) VALUES(11, 'Millennium', 2005, 'Millennium-Stieg Larsson-2005');
INSERT INTO BOOK (AUTHOR_ID, TITLE, RELEASE_YEAR, DESCRIPTION) VALUES(16, 'Gangsters', 2005, 'Gangsters-Klas Ostergren-2005');
INSERT INTO BOOK (AUTHOR_ID, TITLE, RELEASE_YEAR, DESCRIPTION) VALUES(10, 'Easy Money', 2006, 'Easy Money-Jens Lapidus-2006');
INSERT INTO BOOK (AUTHOR_ID, TITLE, RELEASE_YEAR, DESCRIPTION) VALUES(10, 'Never Screw Up', 2008, 'Never Screw Up-Jens Lapidus-2008');
INSERT INTO BOOK (AUTHOR_ID, TITLE, RELEASE_YEAR, DESCRIPTION) VALUES(16, 'Den sista cigaretten', 2009, 'Den sista cigaretten-Klas Ostergren-2009');
INSERT INTO BOOK (AUTHOR_ID, TITLE, RELEASE_YEAR, DESCRIPTION) VALUES(10, 'Life Deluxe', 2011, 'Life Deluxe-Jens Lapidus-2011');
INSERT INTO BOOK (AUTHOR_ID, TITLE, RELEASE_YEAR, DESCRIPTION) VALUES(4, 'Torka aldrig tarar utan handskar: Karleken', 2012, 'Torka aldrig tarar utan handskar: Karleken-Jonas Gardell-2012');
INSERT INTO BOOK (AUTHOR_ID, TITLE, RELEASE_YEAR, DESCRIPTION) VALUES(2, 'Wilful Disregard', 2013, 'Wilful Disregard-Lena Andersson-2013');
INSERT INTO BOOK (AUTHOR_ID, TITLE, RELEASE_YEAR, DESCRIPTION) VALUES(4, 'Torka aldrig tarar utan handskar: Sjukdomen', 2013, 'Torka aldrig tarar utan handskar: Sjukdomen-Jonas Gardell-2013');
INSERT INTO BOOK (AUTHOR_ID, TITLE, RELEASE_YEAR, DESCRIPTION) VALUES(4, 'Torka aldrig tarar utan handskar: Doden', 2013, 'Torka aldrig tarar utan handskar: Doden-Jonas Gardell-2013');
INSERT INTO BOOK (AUTHOR_ID, TITLE, RELEASE_YEAR, DESCRIPTION) VALUES(2, 'Utan personligt ansvar', 2014, 'Utan personligt ansvar-Lena Andersson-2014');
INSERT INTO BOOK (AUTHOR_ID, TITLE, RELEASE_YEAR, DESCRIPTION) VALUES(16, 'Twist', 2014, 'Twist-Klas Ostergren-2014');

-- READER TABLE
INSERT INTO READER (FIRSTNAME, LASTNAME, STREET, CITY, ZIP_CODE) VALUES ('Alois', 'Vomacka', 'Opletalova 1', 'Ostrava','123 45');
INSERT INTO READER (FIRSTNAME, LASTNAME, STREET, CITY, ZIP_CODE) VALUES ('Frantisek', 'Novotny', 'Komentskeho 456/3', 'Bruntal','456 45');
INSERT INTO READER (FIRSTNAME, LASTNAME, STREET, CITY, ZIP_CODE) VALUES ('Igor', 'Dostal', 'Rude armady 245', 'Brno','794 11');
